name: pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             pip install pylint>=2.12.2
      - name: Analysing the code with pylint
        id: pylint
        run: python3 .github/workflows/run_pylint.py
      - name: Generating badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 385e5dc0d1b4f63dffa3de2db8695a69
          filename: test.json
          label: pylint
          message: ${{ steps.pylint.outputs.rating }}
          color: ${{ steps.pylint.outputs.color }}
          namedLogo: Python
          style: flat
      - name: Return final success code
        env:
          linting_status: ${{ steps.pylint.outputs.linting_status }}
        run: python3 .github/workflows/finish_pylint.py
